version: '3.8'

services:
  mysql:
    image: mysql:8.0.33
    container_name: mysql-container
    restart: always
    ports:
      - "3306:3306"
    environment:
      MYSQL_ROOT_PASSWORD: rootpassword
      MYSQL_DATABASE: my_crud_db
      MYSQL_USER: admintzl
      MYSQL_PASSWORD: admintzl123
    volumes:
      - mysql_data:/var/lib/mysql

  redis:
    image: redis:latest
    container_name: redis-container
    restart: always
    ports:
      - "6379:6379"
    volumes:
      - redis_data:/data

  app:
    build: .
    container_name: springboot-app
    restart: always
    ports:
      - "8080:8080"
    depends_on:
      - mysql
      - redis
    environment:
      SPRING_APPLICATION_NAME: common

      # MySQL DB connection
      SPRING_DATASOURCE_URL: jdbc:mysql://mysql:3306/my_crud_db
      SPRING_DATASOURCE_USERNAME: admintzl
      SPRING_DATASOURCE_PASSWORD: admintzl123
      SPRING_DATASOURCE_DRIVER_CLASS_NAME: com.mysql.cj.jdbc.Driver

      # JPA and Hibernate
      SPRING_JPA_HIBERNATE_DDL_AUTO: update
      SPRING_JPA_SHOW_SQL: "true"
      SPRING_JPA_PROPERTIES_HIBERNATE_DIALECT: org.hibernate.dialect.MySQL8Dialect

      # Redis config
      SPRING_REDIS_HOST: redis
      SPRING_REDIS_PORT: 6379


      # Spring Security
      SPRING_SECURITY_USER_NAME: admin
      SPRING_SECURITY_USER_PASSWORD: admin123

      # JWT
      JWT_SECRET: 880002f461676978c2d40c8d8f6e40eaffddd72093055b56deca887def8853acaf9c523a83d49c50c0e4041c593bc7f1d7811c253296f4082fdc0595138fa247c28bf7a78166ad44cd6774e29352516809060e19ef352d0efd79d88454e0bb90ed7086cde1db2aab567dcf527ca685e2303bdd512c2223f3f8002a622a35151ad50fd09eec14769ba278c34e4c1f31e3e937e71d10457917825c6a08b198952bb03cc3709bf5942f994920cb1da5e1720c75e74ffc6f67c7a85de4a97237c401de57cfe375f59eb81486ab21158f2ce045db611fff1dcbbc061a3685b13b4a3a73e6eb33ade131eb11253989c852f869c2af0d8ed056c1a696af99d38df3558c
      JWT_EXPIRATION: 7200000
      RESETPASSWORDLINK: http://localhost:4200/resetpassword

      # Mail settings
      SPRING_MAIL_HOST: smtp.gmail.com
      SPRING_MAIL_PORT: 587
      SPRING_MAIL_USERNAME: tzl.javadeveloper@gmail.com
      SPRING_MAIL_PASSWORD: coff fimy jlte wwtx
      SPRING_MAIL_PROPERTIES_MAIL_SMTP_AUTH: "true"
      SPRING_MAIL_PROPERTIES_MAIL_SMTP_STARTTLS_ENABLE: "true"

volumes:
  mysql_data:
  redis_data:
